#name: Notify on Build Completion

#on:
  #workflow_run:
   # matches:
   #   - workflow_dispatch  # Trigger on manual workflow dispatch
  #    - push:  # Trigger on push events
 #       branches: [ main, development ]  # Only on main and development branches


#jobs:
  #notify:
    #runs-on: ubuntu-latest
    #steps:
    #  - uses: actions/checkout@v2

     # - name: Notify on Build Completion
        #uses: actions/github-script@v6
        #with:
        #  script: |
       #     github.issues.createComment({
      #        issue_number: 0,
     #         owner: 'NadaKamel03',
    #          repo: context.repo.repo,
   #           body: 'The build workflow has completed! Status: ${{ job.status }}'
  #          })
name: Notify on Build Completion

on:
  workflow_dispatch: {}  # Trigger on manual workflow dispatch
  push:  # Trigger on push events
    branches:
      - main
      - development  # Only on main and development branches

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Checked out code"  # Add echo statement here to verify checkout step execution

      - name: Notify on Build Completion
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Script execution started");  // Print at script beginning
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.rest.issues.createComment({
              issue_number: 0,  // Replace with actual issue number (optional)
              owner: NadaKamel03,
              repo: context.repo.repo,
              body: `The build workflow has completed! Status: ${process.env.GITHUB_JOB_STATUS}`
            });
            console.log("Script execution completed");  // Print at script end
